package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;

public class NewContactTest extends TestBase {

    @Test
    public void testNewContact() {
        app.goToNewContactPage();
        app.fillNewContactForm(new ContactData("testname",
                "testname",
                "testname",
                "testname",
                "Moscow"));
        app.submitCreationNewContact();
        app.returnToMainPage();
        app.logout();
    }
}

