// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import java.util.*;
public class NewGroupTest {
  private Map<String, Object> vars;
  @BeforeEach
  public void setUp() {
    Configuration.browser = "chrome";
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
  }
  @Test
  public void newGroup() {
    open("http://localhost/addressbook");
    $(byName("user")).click();
    $(byName("user")).val("admin");
    $(byName("pass")).click();
    $(byName("pass")).val("secret");
    $("input:nth-child(7)").click();
    $(byLinkText("groups")).click();
    $(byName("new")).click();
    WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(1021, 733));
    $(byName("group_name")).click();
    $(byName("group_name")).val("contacts");
    $(byName("group_header")).click();
    $(byName("group_header")).val("phone");
    $(byName("group_footer")).click();
    $(byName("group_footer")).val("number");
    $(byName("submit")).click();
    $(".msgbox").shouldHave(text("A new group has been entered into the address book.\n return to the group page"));
    WebDriverRunner.closeWindow();
  }
}
