package ru.ls.qa.school.addressbook;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;

public class NewContactTest extends TestBase {

    @Test
    public void testNewContact() {
        goToNewContactPage();
        fillNewContactForm(new ContactData("testname",
                "testname",
                "testname",
                "testname",
                "Moscow"));
        submitCreationNewContact();
        returnToMainPage();
        logout();
    }
}

